#!/usr/bin/env bash

# Copyright (C) 2025 Szász Roland
#
# BSPWM configuration file for Debian 12

# ░█▀▀░█▀▀░█▀█░█▀▀░█▀▄░█▀█░█░░
# ░█░█░█▀▀░█░█░█▀▀░█▀▄░█▀█░█░░
# ░▀▀▀░▀▀▀░▀░▀░▀▀▀░▀░▀░▀░▀░▀▀▀

# Defining windows manager to apps to be "copmliant"
export XDG_CURRENT_DESKTOP='bspwm'

# Compatibility fix for Java GUI apps
# Show JAVA applications correctly
export _JAVA_AWT_WM_NONREPARENTING=1

# BSPWM colors
BSPWM_FBC='#81A1C1'
BSPWM_NBC='#2E3440'
BSPWM_ABC='#B48EAD'
BSPWM_PFC='#A3BE8C'

# Bspwm appearance
BSPWM_BORDER='1'
BSPWM_GAP='10'
BSPWM_SRATIO='0.50'

# ░█▀▀░█▀█░█▀█░█▀▀░▀█▀░█▀▀░█░█░█▀▄░█▀█░▀█▀░▀█▀░█▀█░█▀█
# ░█░░░█░█░█░█░█▀▀░░█░░█░█░█░█░█▀▄░█▀█░░█░░░█░░█░█░█░█
# ░▀▀▀░▀▀▀░▀░▀░▀░░░▀▀▀░▀▀▀░▀▀▀░▀░▀░▀░▀░░▀░░▀▀▀░▀▀▀░▀░▀


# Manager Moitors and Workspaces

# Default
default_workspaces() {
	for monitor in `xrandr -q | grep -w 'connected' | cut -d' ' -f1`; do
		bspc monitor "$monitor" -d '' '' '' '' '' '' '' ''
	done
}

# Two monitor setup
two_monitors_workspaces() {
	# change these values according to your system
	# you can use `xrandr -q` to get the names of monitors
	INTERNAL_MONITOR="eDP"
	EXTERNAL_MONITOR="HDMI-A-0"
	if [[ $(xrandr -q | grep "${EXTERNAL_MONITOR} connected") ]]; then
		bspc monitor "$EXTERNAL_MONITOR" -d '' '' '' ''
		bspc monitor "$INTERNAL_MONITOR" -d '' '' '' ''
		bspc wm -O "$EXTERNAL_MONITOR" "$INTERNAL_MONITOR"
	else
		bspc monitor "$INTERNAL_MONITOR" -d '' '' '' '' '' '' '' ''
	fi
}

# Three monitor setup
three_monitors_workspaces() {
	# again, change these values accordingly
	MONITOR_1="eDP"
	MONITOR_2="HDMI-A-0"
	MONITOR_3="HDMI-A-1"
	bspc monitor "$MONITOR_1" -d '' ''
	bspc monitor "$MONITOR_2" -d '' '' ''
	bspc monitor "$MONITOR_3" -d '' '' ''
	bspc wm -O "$MONITOR_2" "$MONITOR_1" "$MONITOR_3"
}

# Uncomment the function that you need (according to your monitor number)
default_workspaces
#two_monitors_workspaces
#three_monitors_workspaces

# BSPWM configuration
bspc config border_width "$BSPWM_BORDER"
bspc config window_gap "$BSPWM_GAP"
bspc config split_ratio "$BSPWM_SRATIO"

bspc config focused_border_color "$BSPWM_FBC"
bspc config normal_border_color "$BSPWM_NBC"
bspc config active_border_color "$BSPWM_ABC"
bspc config presel_feedback_color "$BSPWM_PFC"

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true
bspc config presel_feedback true

# Manage all the unmanaged windows remaining from a previous session.
# “Scan for any orphaned X windows and adopt them into the tiling tree.”
bspc wm --adopt-orphans

# ░█░█░▀█▀░█▀█░█▀▄░█▀█░█░█░░░█▀▄░█░█░█░░░█▀▀░█▀▀
# ░█▄█░░█░░█░█░█░█░█░█░█▄█░░░█▀▄░█░█░█░░░█▀▀░▀▀█
# ░▀░▀░▀▀▀░▀░▀░▀▀░░▀▀▀░▀░▀░░░▀░▀░▀▀▀░▀▀▀░▀▀▀░▀▀▀

# Remove all rules beforehand
bspc rule -r *:*

# Terminal (alway open on workspace no.1)
declare -a terminal_emulator=(Kitty Alacritty)
for i in "${terminal_emulator[@]}"; do
    bspc rule -a $i desktop='^1' follow=on focus=on
done
